### ISSUE TITLE
error while parsing csv file

### ISSUE THREAD

**Issue by gdadade** [michaelgruenstaeudl/SPTSPD#2]
I've downloaded the latest version as gz file.
Running the script caused an error message related to the csv file, see screenshot. Don't know whether the csv file is incorrect or if it is a bug.
![grafik](https://user-images.githubusercontent.com/12762108/70691767-2ba5c380-1cba-11ea-8105-6b9fdef367be.png)

**Comment by Yanjo96** [comment]
Hey :),
could you show the command with which you executed the program and the pip installation error message? There are also small errors in the csv file but I got a different error message so perhabs something in the installation went wrong?

**Comment by gdadade** [comment]
I ran these lines: 
SCRPT=~/Desktop/annonex2embl-0.8.5/scripts/annonex2embl_launcher_CLI.py
INPUT=~/Desktop/ENA/Sinoseris/ITS_Matrix_for_sequence_submission_updated_gd.nex
METAD=~/Desktop/ENA/Sinoseris/Metadata.csv
DESCR="description_of_alignment"
EMAIL=topsecret@world.de
AUTHR="Gabi"

python3 $SCRPT -n $INPUT -c $METAD -o ${INPUT%.nex*}.embl -d $DESCR -e $EMAIL -a $AUTHR

The pip installation did not cause any error. The problem was, that I simply could not find the installed software (see screenshot). That's why I just unpacked the gz file and used this one.
![image](https://user-images.githubusercontent.com/12762108/70717013-7ecc4600-1cbb-11ea-9023-0ac4c82d7274.png)

**Comment by Yanjo96** [comment]
You do not need to run the program from the folder. After the installation via pip it should be enough to type `annonex2embl` in the terminal from any directory. 
You could simply remove `python3` from this line

> python3 $SCRPT -n $INPUT -c $METAD -o ${INPUT%.nex*}.embl -d $DESCR -e $EMAIL -a $AUTHR

and maybe modify the first line like that
```
SCRPT=annonex2embl
```

if there are no other problems, it should work then

**Comment by gdadade** [comment]
Thanks! Now the program is running. I didn't know I should just type `annonex2embl` ...
But I don't think this solved the problem with the csv. It's the same error message just a different color. Is there something wrong with my csv?
![image](https://user-images.githubusercontent.com/12762108/70721244-3a44a880-1cc3-11ea-91d5-2ea6fcbdfe6f.png)

**Comment by Yanjo96** [comment]
Yes, I found 3 problems in the csv file

1. there is an `ü` in the file which you have to replace with an `ue`
2. the name of the qualifer `lat_long` have to be replaced with `lat_lon`
3. The csv file is delimited with `;` but at the moment annonex2embl only recognize `,` as a delimiter. I asked @michaelgruenstaeudl how to handle this problem because in youre case `,` have another function then delimiting the csv file

I will fix this problem three soon and then let you know how it should work.

**Comment by gdadade** [comment]
Thanks! Now it is working. I just exported the csv with comma. But indeed it would be good, if other separators would be supported too.

**Comment by Yanjo96** [comment]
The new parameter `metadelim` makes other separators possible now.
